### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by sm6srw**
### Purpose

Fix failing tests

* Also kill instance reference when Disposed.
* Properly dispose all string writers.

### Declarations

Check these if you believe they are true

- [X] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

@mjkkirschner

### CODE REVIEW

**Comment by mjkkirschner** [comment]
@sm6srw can you say why this is necessary ?

**Comment by sm6srw** [comment]
@mjkkirschner A needed some sleep to understand what really was going on. PTAL!

**Comment by sm6srw** [comment]
@mjkkirschner PTAL!

**Comment by mjkkirschner** [comment]
So the conversion was failing and blocking?

**Comment by mjkkirschner** [comment]
LGTM

**Pull request merged**
